Feature/468,469 partnership receipt memos
fecgov/fecfile-web-app pull request #1046
Opened 2023-05-04 19:09 UTC by mjtravers

#468 
#469

2023-05-10 13:55 UTC, dheitzer requested changes
just one find

2023-05-10 13:55 UTC, dheitzer commented on front-end/src/app/shared/models/transaction-types/PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO.model.ts
> +      committeeClause = committeeClause.slice(0, 97 - parenthetical.length) + '...';
Looks like you'll run into the same issue I ran into on 504 here where the CPD won't validate:  

Recount/Legal Proceedings Account JF Memo:  (Partnership attributions do not require itemization)

is already 97 chars so adding ... will cause this slice to remove the ':' thus invalidating the pattern.  

The solution I recommend (that I made on 504) was to add this special case:

```
const base = 'Recount/Legal Proceedings Account JF Memo: ';
if (hasChildren) {
  return base + ' (Partnership attributions do not require itemization)'
}
```

@AureliaKhorsand said this is acceptable until we increase the CPD field length.

2023-05-11 12:50 UTC, mjtravers commented on front-end/src/app/shared/models/transaction-types/PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO.model.ts
> +      committeeClause = committeeClause.slice(0, 97 - parenthetical.length) + '...';
@dheitzer I am not running into this problem and am able to save transactions without triggering the validation error. Looks like that description plus the "..." is coming in at exactly 100 characters. Are you hitting this validation issue in your testing of the ticket?

2023-05-11 14:33 UTC, dheitzer approved these changes

2023-05-11 17:00 UTC, merged