Feature/642,739 Create in-kind receipt and In-kind out transactions
fecgov/fecfile-web-app pull request #1127
Opened 2023-06-05 13:17 UTC by mjtravers

#642 
#739

2023-06-07 12:17 UTC, toddlees requested changes

2023-06-07 12:17 UTC, toddlees commented on front-end/src/app/shared/models/transaction-groups/transaction-group-aa.model.ts
> +      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
Did you mean to add memo_code rather than category_code?

2023-06-07 20:50 UTC, mjtravers commented on front-end/src/app/shared/models/transaction-groups/transaction-group-aa.model.ts
> +      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
I added category code here so that it was not set read-only in the form. This field is not pulling values from the parent schedule A but should allow the user to select a category code for the schedule B transaction.

2023-06-08 13:47 UTC, toddlees commented on front-end/src/app/shared/models/transaction-groups/transaction-group-aa.model.ts
> +      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
<img width="1169" alt="image" src="https://github.com/fecgov/fecfile-web-app/assets/97105825/c7637fa4-d87c-4f4d-8c2d-50bdfe0b79c8">

I think the user is allowed to edit that part.  The schema shows it as variable, like the memo

2023-06-08 13:50 UTC, toddlees commented on front-end/src/app/shared/models/transaction-groups/transaction-group-aa.model.ts
> +      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
If it's not editable, should it be in the interface/schema at all?  it will never be populated

2023-06-08 14:05 UTC, toddlees approved these changes

2023-06-08 14:05 UTC, toddlees commented on front-end/src/app/shared/models/transaction-groups/transaction-group-aa.model.ts
> +      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
I just figured out what i'm saying and what you did after testing it locally 🤦

2023-06-08 15:09 UTC, Elaine-Krauss-TCG approved these changes

2023-06-08 16:34 UTC, merged