Feature/1177 Add date range validation to Date Incurred input
fecgov/fecfile-web-app pull request #1259
Opened 2023-07-18 20:23 UTC by mjtravers

#1177

2023-07-20 18:06 UTC, toddlees requested changes
Does this mean we can remove the `doMemoCodeDateCheck` flag from TransactionType since loan receipts won't ever be outside report dates now?

2023-07-20 20:30 UTC, mjtravers commented
> Does this mean we can remove the `doMemoCodeDateCheck` flag from TransactionType since loan receipts won't ever be outside report dates now?

Yes, that flag was temporary and waiting for this ticket. The flag has been removed from the transaction type.

2023-07-21 15:03 UTC, toddlees commented on front-end/src/app/shared/models/transaction-types/LOAN_RECEIVED_FROM_INDIVIDUAL_RECEIPT.model.ts
> -  override formTitle = 'Reciept';
thank you! that is a common typo of mine

2023-07-21 15:08 UTC, toddlees approved these changes

2023-07-21 15:38 UTC, merged