Feature/863 in kind contribution to candidate take two
fecgov/fecfile-web-app pull request #1316
Opened 2023-08-11 20:21 UTC by Elaine-Krauss-TCG

#863

2023-08-11 22:24 UTC, Elaine-Krauss-TCG commented
Initial testing hasn't revealed any issues, but this needs further testing and more code coverage before I'll be finished with it...

2023-08-14 12:49 UTC, toddlees requested changes, later dismissed

2023-08-14 12:49 UTC, toddlees commented on front-end/src/app/shared/components/inputs/committee-input/committee-input.component.ts
> -        this.form.get(this.templateMap.committee_name)?.setValue(value);
Is there a place in the new code where the committee_name is "bound" to the organization_name when `organization_name` and `committee_name` need to be redundant?

If not, the transacion type form util could add a subscription on the condition that the transactionType has the flag, copyOrgNameIntoCommitteeName.  that value could default to true in the transactionType class, and be overwritten to false in the transactions you've now introduced.

2023-08-16 18:31 UTC, Elaine-Krauss-TCG commented on front-end/src/app/shared/components/inputs/committee-input/committee-input.component.ts
> -        this.form.get(this.templateMap.committee_name)?.setValue(value);
Matt wound up re-adding this, so this issue should be resolved

2023-08-16 18:31 UTC, Elaine-Krauss-TCG commented
![image](https://github.com/fecgov/fecfile-web-app/assets/104506225/8ccc79c3-bb42-4f8a-9deb-25289334b4cd)

2023-08-17 19:37 UTC, mjtravers approved these changes

2023-08-17 19:37 UTC, merged