FEC-1296: updated radio button styles
fecgov/fecfile-web-app pull request #1383
Opened 2023-09-20 16:06 UTC by andrew-bowers-tcg

Updated radio button styling based on wireframe/mock.

2023-09-20 18:00 UTC, mjtravers requested changes
See inline comment about the use of !important

2023-09-20 18:00 UTC, mjtravers commented on front-end/src/assets/styles/theme.css
> +  padding-bottom: 5px !important;
I find using !important to be dangerous. Is there a way to rework the precedence of that padding-bottom directive without using !important? Order of declaration in the style sheet file is one way to affect precedence.

2023-09-20 21:12 UTC, andrew-bowers-tcg commented on front-end/src/assets/styles/theme.css
> +  padding-bottom: 5px !important;
The !important line there was an accidental commit. Should be removed now. Also I will refrain from using it in the future!

2023-09-21 14:35 UTC, mjtravers approved these changes

2023-09-21 14:35 UTC, merged