Feature/526,1069 Add loan pull forward feature
fecgov/fecfile-web-app pull request #1388
Opened 2023-09-22 10:58 UTC by mjtravers

#1069

2023-09-22 20:05 UTC, toddlees requested changes

2023-09-22 20:05 UTC, toddlees commented on front-end/src/app/reports/transactions/transaction-container/transaction-container.component.ts
> +    return (
Nice to have:
how about one function 
```
transctionCardinality(): number {
  if(isPulledForwardLoan(this.transaction) return 1;
  return (this.transaction?.transactionType?.dependentChildTransactionTypes?.length ?? 1)+ 1
}
```

then the html would be `*ngIf="transactionCardinality() === 1 "` and so on in

2023-09-22 20:05 UTC, toddlees commented on front-end/src/app/shared/components/inputs/loan-terms-dates-input/loan-terms-dates-input.component.ts
> +      this.store
i'm starting to think we should have the active transaction in the store so we don't have to pass it through all the component inputs

2023-09-22 20:05 UTC, toddlees commented on front-end/src/app/shared/components/inputs/loan-terms-dates-input/loan-terms-dates-input.component.ts
> +      this.store
then we could also access it as an observable and act on it as it changes.  Definitely not a thing to do right now but a thought

2023-09-22 20:05 UTC, toddlees commented on front-end/src/app/shared/models/schc-transaction-type.model.ts
> +      this.navigationControls.continueControls = [SAVE_LIST_CONTROL];
I changed the order of the test in the LOAN_RECEIVED_FROM_INDIVIDUAL so that it tested a pull-forward before a new loan, and this mutation persisted.  Anyway you can return a new navigationControls object instead of changing the state of the one tied to the transaction type instance?

```
if(isPulledForwardLoan(transaction) && this.navigationControls) {
return new TransactionNavigationControls(this.navigationControls.inlineControls, this.navigationControls.cancelControls, [SAVE_LIST_CONTROL]);
}
```

2023-09-22 21:00 UTC, mjtravers commented on front-end/src/app/shared/components/inputs/loan-terms-dates-input/loan-terms-dates-input.component.ts
> +      this.store
Agreed. We have our fancy ngrx state manager and haven't been leveraging it much

2023-09-22 21:06 UTC, mjtravers commented on front-end/src/app/reports/transactions/transaction-container/transaction-container.component.ts
> +    return (
Oooh. I've added it in.

2023-09-22 21:08 UTC, mjtravers commented on front-end/src/app/shared/models/schc-transaction-type.model.ts
> +      this.navigationControls.continueControls = [SAVE_LIST_CONTROL];
Much better. Done.

2023-09-25 13:19 UTC, toddlees approved these changes

2023-09-25 15:18 UTC, merged