Feature/171 Add tier 1 reattribution screen
fecgov/fecfile-web-app pull request #1520
Opened 2023-11-13 23:12 UTC by mjtravers

#171

2023-11-27 15:08 UTC, toddlees requested changes

2023-11-27 15:08 UTC, toddlees commented on front-end/src/app/reports/transactions/transaction-container/transaction-container.component.ts
> +      this.activatedRoute.snapshot.queryParamMap.get('reattribution') ||
checking the query params in the route should probably be the responsibility of the resolver.  the condition below (...isReattRedes...) would work for new and existing transactions if the resolver sets it up properly

2023-11-27 15:08 UTC, toddlees commented on front-end/src/app/reports/transactions/transaction-list/transaction-list-table-base.component.ts
> +        transaction.transactionType.scheduleId === ScheduleIds.A &&
According to the ticket, it's only possible to reattribute tier 1's so we'll want to disable if they have a parent

2023-11-27 16:13 UTC, mjtravers commented on front-end/src/app/reports/transactions/transaction-container/transaction-container.component.ts
> +      this.activatedRoute.snapshot.queryParamMap.get('reattribution') ||
This line of code turned out to be OBE the following code and I was able to remove it.

2023-11-27 16:13 UTC, mjtravers commented on front-end/src/app/reports/transactions/transaction-list/transaction-list-table-base.component.ts
> +        transaction.transactionType.scheduleId === ScheduleIds.A &&
Good catch. I added a check for the parent_transaction_id

2023-11-27 16:20 UTC, dheitzer commented on front-end/src/app/shared/models/reattribution-redesignation/reattribution-to.model.ts
> +        'The information in this rattribution will automatically create a related receipt. Review the receipt, or continue without reviewing and "Save transactions."',
Typo here.  Should be 'reattribution'

2023-11-27 16:30 UTC, dheitzer commented on front-end/src/app/shared/resolvers/transaction.resolver.ts
> +                const reattributed = transactions.reattributed;
The resolver could fail here if undefined (404 from service for example) so prob need to add truthy check here to be graceful.

2023-12-01 17:57 UTC, Elaine-Krauss-TCG approved these changes

2023-12-01 18:02 UTC, toddlees approved these changes

2023-12-01 18:02 UTC, toddlees commented on front-end/src/app/shared/models/transaction-type.model.ts
> +  abstract getNewTransaction(properties?: any): Transaction; // Factory method to create a new Transaction object with default property values for this transaction type
is properties used anywhere?

2023-12-01 18:02 UTC, toddlees commented on front-end/src/app/shared/components/transaction-type-base/transaction-type-base.component.spec.ts
> +  xit('should save on save event', fakeAsync(() => {
does this still fail?

2023-12-01 21:39 UTC, mjtravers commented on front-end/src/app/shared/components/transaction-type-base/transaction-type-base.component.spec.ts
> +  xit('should save on save event', fakeAsync(() => {
This unit test has been fixed and is now back in the rotation.

2023-12-01 21:39 UTC, mjtravers commented on front-end/src/app/shared/models/transaction-type.model.ts
> +  abstract getNewTransaction(properties?: any): Transaction; // Factory method to create a new Transaction object with default property values for this transaction type
Ah, good catch. This is OBE code from a previous iteration of managing the reattribution overlay of properties. It has been removed.

2023-12-01 21:49 UTC, merged