Feature/1563 Make save buttons disable on click and re-enable after process is complete
fecgov/fecfile-web-app pull request #1573
Opened 2023-12-06 21:36 UTC by sasha-dresden

Also added a bunch of tests to pass the 80% mark

2023-12-11 15:27 UTC, toddlees requested changes

2023-12-11 15:27 UTC, toddlees commented on front-end/src/app/shared/components/navigation-control/navigation-control.component.html
>      *ngIf="controlType === 'dropdown'"
we'll want to disable this dropdown as well.  It allows the user to save and add something from the list

2023-12-11 15:27 UTC, toddlees commented on front-end/src/app/shared/components/transaction-type-base/triple-transaction-type-base.component.ts
> +  override get confirmation$(): Observable<boolean> {
WOW! This is a really impressive way of declaring the confirmations for each part once AND in their own component.

2023-12-11 15:39 UTC, sasha-dresden commented on front-end/src/app/shared/components/navigation-control/navigation-control.component.html
>      *ngIf="controlType === 'dropdown'"
Oh good catch. I added a commit to add the "or processing" to the dropdown as well.

2023-12-12 14:26 UTC, toddlees approved these changes

2023-12-14 19:48 UTC, sasha-dresden commented
Updated code to make use of spinner store.
This reduced the need for passing the processing variable up and down the component hierarchy and also simplified the code.
I am now reusing the single click directive which has been updated to subscribe to the spinner store for updating the disable state.
I also update the ApiService::put and ::post methods so that there is a new Boolean variable it can accept which defaults to false, but if passed as true will use the Spinner variation.

The one potential issue with all of this is that the button gets disabled immediately on click, which is important to prevent double click submissions, however, if the button click doesn't result in an api call (for example if the form fails to validate) there are no calls to re-enable the button. In order to handle this situation, I allowed the button to re-enable itself through the directive after a delay, if the spinner status is false.

2023-12-14 21:12 UTC, mjtravers approved these changes

2023-12-14 21:12 UTC, merged