Feature/1488 - F24 Amendment
fecgov/fecfile-web-app pull request #1666
Opened 2024-01-11 20:43 UTC by Elaine-Krauss-TCG

[App#1488](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1488)

2024-01-12 18:26 UTC, toddlees requested changes

2024-01-12 18:26 UTC, toddlees commented on front-end/src/app/shared/services/report.service.ts
> +    return this.apiService.post(`${this.apiEndpoint}/${report.apiToken}/${report.id}/amend/`, {});
`apiToken` is a bit misleading about what this does.  Maybe `apiPath` or `apiPrefix`?

I think you can avoid all of this routing with my comment in the api pr though.  Just keep this url what it was before and have the api handle the amending
https://github.com/fecgov/fecfile-web-api/pull/666#pullrequestreview-1818806364

2024-01-12 22:14 UTC, toddlees approved these changes

2024-01-13 14:19 UTC, mjtravers approved these changes

2024-01-13 14:19 UTC, merged