Feature/1722 - Add a preparePayload function to these three services to strip out unnecessary data from being sent to the api.
fecgov/fecfile-web-app pull request #1753
Opened 2024-02-27 21:39 UTC by sasha-dresden

2024-03-05 14:21 UTC, toddlees requested changes

2024-03-05 14:21 UTC, toddlees commented on front-end/src/app/shared/interfaces/table-list-service.interface.ts
> +    if (!obj[key] || (typeof obj[key] === 'object' && Object.keys(obj[key]).length === 0)) delete obj[key];
Falsey values and nulls are data too.  If the intent is to set a boolean to False or to remove data from a previously populated field this method will undo that change.

2024-03-06 15:19 UTC, sasha-dresden commented on front-end/src/app/shared/interfaces/table-list-service.interface.ts
> +    if (!obj[key] || (typeof obj[key] === 'object' && Object.keys(obj[key]).length === 0)) delete obj[key];
Fixed that. Sends over empty data now. Also fixed a few misspellings I noticed.

2024-03-08 23:44 UTC, toddlees approved these changes

2024-03-08 23:44 UTC, merged