Feature/1906 - Rework tables so all have same styling and move results to bottom
fecgov/fecfile-web-app pull request #1931
Opened 2024-05-14 18:44 UTC by sasha-dresden

Issue: #1906

2024-05-15 10:41 UTC, mjtravers requested changes
A small label change requested. Also, what is the default number of rows to show on a table, 5 or 10?

2024-05-15 10:41 UTC, mjtravers commented on front-end/src/app/shared/components/table/table.component.html
> +          <span class="paginator-text">Results per table:</span>
Should this be "Results per page:"?

2024-05-15 10:41 UTC, mjtravers commented on front-end/src/app/shared/components/table/table.component.html
> +        <span>Results per table:</span>
Should this be "Results per page:"?

2024-05-15 15:47 UTC, sasha-dresden commented on front-end/src/app/shared/components/table/table.component.html
> +          <span class="paginator-text">Results per table:</span>
Ah I didn't catch that. The old way was "table" and there wasn't a specific point to change it to "page" however all the wireframes had "page". Changed it to page.

2024-05-15 15:49 UTC, sasha-dresden commented on front-end/src/app/shared/components/table/table.component.html
> +          <span class="paginator-text">Results per table:</span>
As for the default number of rows, there isn't one. Some pages had their default as 10, others as 5.

2024-05-16 11:13 UTC, mjtravers approved these changes

2024-05-16 11:13 UTC, merged