Feature/1549 - Update ESlint
fecgov/fecfile-web-app pull request #2156
Opened 2024-08-29 19:17 UTC by Elaine-Krauss-TCG

[Fecfile#1549](https://fecgov.atlassian.net/browse/FECFILE-1549)

2024-09-04 13:27 UTC, toddlees requested changes

2024-09-04 13:27 UTC, toddlees commented on front-end/src/app/committee/manage-committee/manage-committee.component.ts
>        return;
looks like we can remove the identifier and the lint escape
```
} catch {
```
https://stackoverflow.com/a/56001361

2024-09-06 15:38 UTC, Elaine-Krauss-TCG commented on front-end/src/app/committee/manage-committee/manage-committee.component.ts
>        return;
Great idea!  Done :+1:

2024-09-20 13:09 UTC, toddlees approved these changes

2024-09-20 13:28 UTC, merged