feature/1693 - Commenting out dead links
fecgov/fecfile-web-app pull request #2260
Opened 2024-10-15 15:43 UTC by sasha-dresden

2024-10-17 14:41 UTC, dheitzer approved these changes

2024-10-21 14:02 UTC, Elaine-Krauss-TCG approved these changes

2024-10-21 14:58 UTC, toddlees requested changes
I see the ticket instructed you to comment out the links.  I've updated it to remove them instead so we don't have commented code in the codebase

2024-10-21 15:22 UTC, sasha-dresden commented
> I see the ticket instructed you to comment out the links. I've updated it to remove them instead so we don't have commented code in the codebase

Deleted the commented out code

2024-10-22 13:38 UTC, toddlees approved these changes

2024-10-22 13:38 UTC, merged