feature/1600 - Add Security Notification page
fecgov/fecfile-web-app pull request #2266
Opened 2024-10-17 18:50 UTC by sasha-dresden

Issue [FECFILE-1600](https://fecgov.atlassian.net/browse/FECFILE-1600)

2024-10-21 14:20 UTC, Elaine-Krauss-TCG approved these changes

2024-10-23 22:26 UTC, toddlees requested changes

2024-10-23 22:26 UTC, toddlees commented on front-end/src/app/layout/layout.component.html
> -    <div class="container">
It looks like this change is having an effect on the header on wide views.  I don't think there is supposed to be a change to the header as a result of this ticket

As implemented:
![image](https://github.com/user-attachments/assets/13ce8b08-4d53-4677-a341-52e96adb9a3d)

On Dev:
![image](https://github.com/user-attachments/assets/08bd59de-e5b7-412a-8143-77e6ea513f31)

2024-10-28 13:27 UTC, toddlees approved these changes

2024-10-28 13:27 UTC, merged