Feature/392 - Ensure that the Committee Account Info page is fully readable by screen readers
fecgov/fecfile-web-app pull request #2403
Opened 2024-11-25 14:09 UTC by Elaine-Krauss-TCG

Ticket link: [here](https://fecgov.atlassian.net/browse/FECFILE-392)

Related PRs: N/A

2024-11-25 16:24 UTC, dheitzer approved these changes

2024-11-25 17:22 UTC, sasha-dresden approved these changes

2024-11-27 13:31 UTC, toddlees requested changes
![image](https://github.com/user-attachments/assets/1da6a564-e76f-44eb-b38f-dd6ceb6b09d8)
Phone needs an accessible name or linked title

2024-12-06 14:25 UTC, toddlees approved these changes

2024-12-06 14:25 UTC, merged