feature/1833 - Update h5 elements to spans in two places. Kept same look. Added alt text to blue plus image.
fecgov/fecfile-web-app pull request #2427
Opened 2024-11-27 19:43 UTC by sasha-dresden

Issue [FECFILE-1833 ](https://fecgov.atlassian.net/browse/FECFILE-1833)

2024-12-05 14:01 UTC, toddlees requested changes

2024-12-05 14:01 UTC, toddlees commented on front-end/src/app/committee/select-committee/select-committee.component.html
> +          <img src="assets/img/blue-plus.png" alt="blue plus" />
The AC has this alt text saying 'Create a new committee'

2024-12-05 15:51 UTC, sasha-dresden commented on front-end/src/app/committee/select-committee/select-committee.component.html
> +          <img src="assets/img/blue-plus.png" alt="blue plus" />
Thanks! Got that fixed.

2024-12-09 13:40 UTC, toddlees approved these changes

2024-12-09 13:40 UTC, merged