[WIP] Adds Schedule A Transaction Selection
fecgov/fecfile-web-app pull request #274
Opened 2022-05-11 21:35 UTC by toddlees

@mjtravers I tried andi on the page and it alerted me to the use of aria-hidden.  Based on this [article](http://web-accessibility.carnegiemuseums.org/code/accordions/) I believe primeng is using aria-hidden appropriately and the alert can be ignored

2022-05-13 15:41 UTC, mjtravers requested changes
Per our discussion, please rename the component so it specifically references being an F3X-centric component and the 4 code smells. Thx

2022-05-13 15:41 UTC, mjtravers commented on front-end/src/app/transactions/transaction-type-picker/transaction-type-picker.component.ts
> +  report: F3xSummary | undefined;
I think we can change this F3xSummary type to the Report interface type. Is this component only for F3X transactions or will their be transactions for other form types down the road? If not, we can leave it as F3xSummary

2022-05-16 00:41 UTC, mjtravers requested changes
I am seeing errors in the unit test output. They don't stop the testing but it should be sorted out before merging to develop. Here's a screen shot:
![cr-app228-unit-test-errors](https://user-images.githubusercontent.com/2971785/168502019-ea114ce1-666b-4ac9-a988-77b8f6b27bb8.png)

2022-05-16 16:35 UTC, toddlees commented
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/97105825/168640955-6830c3e8-d77e-428b-afe4-8060d6cdf4a4.png">
@mjtravers addressed the messages coming up during the unit tests.  adding routertestingmodule silenced them

2022-05-16 23:07 UTC, mjtravers approved these changes

2022-05-16 23:07 UTC, merged