233 group e jf transfers
fecgov/fecfile-web-app pull request #358
Opened 2022-06-24 21:45 UTC by dheitzer

2022-06-27 13:08 UTC, Elaine-Krauss-TCG approved these changes
Looks good all around

2022-06-27 18:04 UTC, dheitzer commented on front-end/src/app/transactions/transaction-group-e/transaction-group-e.component.ts
> +    this.form.get('entity_type')?.setValue(this.contactTypeOptions[0].code);
Just wanted to point this out - I had to add this because  p-dropdown displays the first item in the list (autoDisplayFirst defaults to true https://www.primefaces.org/primeng/dropdown) however it doesn't set it in the form.  Therefore, I was getting "IND" when I saved (instead of "COM" since this is the first in the list).  I think we'll need to do add this for the other transactions so we may want to consider adding it to the base class?

2022-06-27 19:00 UTC, toddlees commented on front-end/src/app/transactions/transaction-group-e/transaction-group-e.component.ts
> +    this.form.get('entity_type')?.setValue(this.contactTypeOptions[0].code);
Isn't the only option COM based on line 33?  If primeng is picking "IND" that means we're providing it the wrong list of options somehow right?

2022-06-27 19:27 UTC, mjtravers requested changes
All looks good except I am not getting the red required error message for Date Received when saving and the calendar input is blank. See here:
![image](https://user-images.githubusercontent.com/2971785/176019357-cbf67156-fcb1-4a2b-89ab-18893ba41b7a.png)

2022-06-27 19:38 UTC, mjtravers commented on front-end/src/app/transactions/transaction-group-e/transaction-group-e.component.ts
> +    this.form.get('entity_type')?.setValue(this.contactTypeOptions[0].code);
I traced this and the problem is actually in the resetForm() method in the transaction-type-base.component.ts. A better solution is to create a defaultEntityType property to the base component class and have it default to ContactTypes.INDIVIDUAL. Subsequent iterations of the form can set the defaultEntityType to values other than ContactTypes.INDIVIDUAL. The line at 150 in transaction-type-base.components.ts can replace ContactTypes.INDIVIDUAL with this.defaultEntityType and the override of ngOnInit can be removed from transaction-group-e-component.ts

2022-06-27 19:51 UTC, toddlees commented on front-end/src/app/transactions/transaction-group-e/transaction-group-e.component.ts
> +    this.form.get('entity_type')?.setValue(this.contactTypeOptions[0].code);
@mjtravers if we don't care about which option of the correct options come first, we could just replace line 150 with @dheitzer 's code: `entity_type: this.contactTypeOptions[0].code`

2022-06-28 19:40 UTC, toddlees approved these changes

2022-06-28 20:37 UTC, mjtravers approved these changes
The required warning for the date field is not working but looks to be broken in develop branch now, too. Passing ticket for CR and the date required warning will be examined/fixed in a follow on ticket.

2022-06-28 20:39 UTC, merged