[WIP] Feature/328 logout for login dot gov
fecgov/fecfile-web-app pull request #394
Opened 2022-07-18 18:39 UTC by dheitzer

2022-09-01 17:19 UTC, dheitzer commented
This one is ready for CR

2022-09-01 20:31 UTC, Elaine-Krauss-TCG approved these changes

2022-09-02 13:23 UTC, MitchellTCG commented
@toddlees Can you please CR this pull?

2022-09-06 00:07 UTC, toddlees approved these changes

2022-09-06 00:07 UTC, toddlees commented on front-end/src/app/shared/services/api.service.ts
> +  public getAbsoluteUrl<T>(
I think the purpose of the api url is that it's for interactions with the (FECfile) api.  Requests to other api's should be in their own services

2022-09-06 00:07 UTC, toddlees commented on front-end/src/app/shared/services/login.service.ts
> +      window.location.href = environment.loginDotGovLogoutUrl || "";
Seems like this is the fix 👍 .  As for the code before, `pipe(tap(...))` [is for side effects](https://rxjs.dev/api/operators/tap) and is redundant to the subscribe below where line 71 and 72 would be more appropriate

2022-09-06 03:15 UTC, toddlees requested changes

2022-09-06 03:15 UTC, toddlees commented on front-end/src/app/shared/services/login.service.ts
> +      window.location.href = environment.loginDotGovLogoutUrl || "";
This seems to be causing the unit tests to fail.  Maybe there's a way to turn this off when it's running unit tests

2022-09-06 13:04 UTC, toddlees approved these changes

2022-09-06 13:04 UTC, merged