Feature/111 intl phone num take two
fecgov/fecfile-web-app pull request #541
Opened 2022-08-29 20:12 UTC by dheitzer

2022-08-30 14:04 UTC, Elaine-Krauss-TCG commented
I was interested in how the field would actually look on the front-end, so I pulled and went to make a Contact.  Unfortunately, I think I found a bug?

When I selected a country code (Malaysia, chosen at random), if I typed in a phone number, it shows an error "this field must contain 10 alphanumeric characters" when there are 6 characters entered,
![image](https://user-images.githubusercontent.com/104506225/187457409-3da8e2e1-0d28-4bef-bde4-18d30d9238b9.png)

but then it shows "this field cannot contain more than 10 alphanumeric characters" at 7 entered characters.
![image](https://user-images.githubusercontent.com/104506225/187457890-e4ca09fc-746a-44fb-a41c-8b93098091f7.png)

2022-08-30 14:08 UTC, Elaine-Krauss-TCG commented
The error message appears at varying points depending on the length of the country code
![image](https://user-images.githubusercontent.com/104506225/187458806-48b8e70b-6019-40ba-9941-63c1af9931c3.png)

![image](https://user-images.githubusercontent.com/104506225/187458932-093ace25-51ba-4878-a77e-5d0a429bf89d.png)

2022-08-30 14:10 UTC, dheitzer commented
@Elaine-Krauss-TCG did you rebuild your client on that branch to pull in the latest fecfile-validation change? There was a needed validation change for this field that could be causing this behavior.

2022-08-30 14:30 UTC, Elaine-Krauss-TCG commented
> @Elaine-Krauss-TCG did you rebuild your client on that branch to pull in the latest fecfile-validation change? There was a needed validation change for this field that could be causing this behavior.

After talking with David about this, we found that fully rebuilding the front-end did solve my problem, but there is another error altogether.  If you create a new contact and type in a phone number without changing the country code, it does not recognize the phone number as having a valid length when it should.

2022-08-31 12:34 UTC, dheitzer commented
> 

@Elaine-Krauss-TCG this bug has been addressed and this should be ready for CR now.

2022-08-31 12:50 UTC, Elaine-Krauss-TCG approved these changes

2022-08-31 13:11 UTC, Elaine-Krauss-TCG approved these changes

2022-08-31 16:00 UTC, toddlees requested changes
I think there's an unimplemented requirement:
>ZIP (A/N-9, not required only if Country is NOT United States) [validate that optional appears if state chosen]

Additionally there seems to be a problem with the requirements.  Having the number after the country code always be 10 (no more no less) breaks functionality for countries with more (China 11 digits) and less (Chili 9 digits) digits.  We can probably pass this and make a followup ticket for expanding that rule.  Similarly we'll want to make a ticket for allowing spaces, parentheses, and hyphens in the input (stripping them out to save).

2022-08-31 16:00 UTC, toddlees commented on front-end/src/app/shared/components/fec-intl-tel-input/fec-intl-tel-input.component.html
> +<div>
We've been following a convention of avoiding abbreviation when possible.  Clarity of code is highly impactful and shrinking variable/class/filenames doesn't gain us much.  I'd highly recommend spelling out `intl` and `tel` as `international` and `telephone` or just `phone`

2022-08-31 16:02 UTC, toddlees commented on front-end/src/app/shared/components/fec-intl-tel-input/fec-intl-tel-input.component.ts
> +  private iti: intlTelInput.Plugin | null = null;
I see that this comes from the example code from their site, but could we spell this out more.  When i first encountered `iti` in the spec above I couldn't even guess what it meant.

2022-09-01 20:32 UTC, Elaine-Krauss-TCG approved these changes

2022-09-02 14:49 UTC, Elaine-Krauss-TCG approved these changes

2022-09-06 02:51 UTC, toddlees approved these changes

2022-09-06 03:04 UTC, merged