Feature/553 footer
fecgov/fecfile-web-app pull request #599
Opened 2022-09-28 18:51 UTC by Elaine-Krauss-TCG

#553 

Adds the footer to the website.

Also corrects an issue where the "karla" and "gandhi" fonts were not loading correctly.

2022-09-28 18:55 UTC, Elaine-Krauss-TCG commented
Failed unit test is not failing on local, and is also not touched by any changes in this ticket...
![image](https://user-images.githubusercontent.com/104506225/192865589-708d2fb4-7194-48e9-9130-18f147b56686.png)

2022-09-30 13:12 UTC, mjtravers requested changes
There is a white padding around the footer left, bottom, and right side that does not appear in the wire frame. Here is a screen shot showing the extra padding when the footer blue should to to the left, right, and bottom edges
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/73c3a144-9343-4577-9da5-70caa46c7741)
Sending back to In Progress

2022-09-30 14:50 UTC, Elaine-Krauss-TCG commented
> There is a white padding around the footer left, bottom, and right side that does not appear in the wire frame. Here is a screen shot showing the extra padding when the footer blue should to to the left, right, and bottom edges ![image.png](https://camo.githubusercontent.com/1282bec65596dac9c308251bbaa3470ac23c5af17887eb5d9263defc0024920c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631623966633732643939623666373836653064373938632f37336333613134342d393334332d343537372d396461352d373063616134366337373431) Sending back to In Progress

Styling updates have been made to the layout component in order to eliminate this gap.

2022-10-03 16:50 UTC, mjtravers approved these changes

2022-10-03 16:50 UTC, merged