Feature/237 aggregation groups
fecgov/fecfile-web-app pull request #610
Opened 2022-10-07 20:03 UTC by Elaine-Krauss-TCG

[#237](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/237)

2022-10-11 15:08 UTC, dheitzer commented on front-end/src/app/shared/models/scha-transaction.model.ts
> +export type AggregationGroup =
Do we want to make this an enum instead (similar to ScheduleATransactionGroups for example)?

2022-10-11 15:09 UTC, dheitzer commented on front-end/src/app/shared/models/transaction-types/EARMARK_RECEIPT.model.ts
> +      aggregation_group: "General",
If we make AggregationGroup an enum, we can reference it directly here (and aggregation_group will be typed)

2022-10-11 16:43 UTC, mjtravers requested changes
See inline comments for requested changes

2022-10-11 16:43 UTC, mjtravers commented on front-end/src/app/shared/models/transaction-types/EARMARK_RECEIPT.model.ts
> +      aggregation_group: "General",
I agree with David, an enum has a bit more flexibility. Here it would be referenced by something like AggregationGroup.GENERAL rather than "General". That way if the internal ID ever changes or something of the sort then the enum is changed and the references in the code can stay as is. See what was done with the combination of enums and typing for F3XFormTypes and F3xFormType in f3x-summary.model.ts

2022-10-12 14:05 UTC, mjtravers approved these changes

2022-10-12 14:06 UTC, merged