Feature/626
fecgov/fecfile-web-app pull request #686
Opened 2022-11-16 14:28 UTC by toddlees

#626

2022-11-16 16:53 UTC, dheitzer commented
Along this vein, do we know if Transaction interface parent_transaction_id is still needed? It seems to be redundant with parent_transaction.id from an initial look, but I could be missing something.

2022-11-17 17:38 UTC, Elaine-Krauss-TCG commented
I ran the E2E tests on this branch, and everything looks good.

![image](https://user-images.githubusercontent.com/104506225/202516785-c3ef63e4-485f-45fd-8ec2-c1a4e21a3b42.png)

One test failed, but it passed 3/3 times on being re-run individually.

2022-11-17 17:38 UTC, Elaine-Krauss-TCG approved these changes

2022-11-18 12:45 UTC, mjtravers requested changes
Now that the TransactionType interface is defining the transaction and childTransactionType properties as optional with the "?", can we safely remove those properties from the classes implementing the interface that have those 2 properties set to values such as:

transaction = undefined;
transaction?: SchATransaction = undefined;
transaction: SchATransaction | undefined = undefined;
transaction?: Transaction;
childTransactionType = undefined;

Also, do we need the "parent?: SchATransaction;" and "contact = undefined;" properties in PAC_RECOUNT_RECEIPT.model.ts and TRANSFER.model.ts?

If we can remove those property declarations safely, I'd like to merge develop into this branch to pickup the new transaction type models recently merged and then prune all those superfluous property declarations from the transaction type model class definitions.

2022-11-18 20:39 UTC, mjtravers approved these changes

2022-11-18 20:40 UTC, merged