Partnership National Party Pres Nominating Convention Account
fecgov/fecfile-web-app pull request #856
Opened 2023-02-08 14:01 UTC by toddlees

#636 
#637

2023-02-10 20:51 UTC, Elaine-Krauss-TCG approved these changes

2023-02-14 16:41 UTC, dheitzer approved these changes

2023-02-15 21:58 UTC, mjtravers requested changes
The develop branch has been merged in but I am seeing a disconnect in transaction_type_identifiers and not seeing and entry for the new transaction types in the cypress e2e tests

2023-02-15 21:58 UTC, mjtravers commented on front-end/src/app/shared/models/scha-transaction.model.ts
>    PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
I'm seeing the transaction_type_identifier in the spec to be PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT and not PARTNERSHIP_NATIONAL_PARTY_PRES_NOMINATING_CONVENTION_ACCOUNT

2023-02-15 21:58 UTC, mjtravers commented on front-end/src/app/shared/models/scha-transaction.model.ts
> +  PARTNERSHIP_NATIONAL_PARTY_PRES_NOMINATING_CONVENTION_ACCOUNT_MEMO = 'PARTNERSHIP_NATIONAL_PARTY_PRES_NOMINATING_CONVENTION_ACCOUNT_MEMO',
also the memo transasction_type_identifier in the spec is different. I see PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO in the spec

2023-02-16 18:53 UTC, mjtravers approved these changes

2023-02-16 18:53 UTC, merged