Feature/679 credit card payment receipts
fecgov/fecfile-web-app pull request #889
Opened 2023-02-27 21:04 UTC by Elaine-Krauss-TCG

[App#679](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/679)

2023-02-28 15:24 UTC, toddlees requested changes

2023-02-28 15:24 UTC, toddlees commented on front-end/src/app/transactions/transaction-group-d/transaction-group-d.component.ts
> +        'payee_last_name',
I don't think all of these fields are part of the group D https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1262101402
there shouldn't be individual contact fields like last name and first name

2023-03-01 21:21 UTC, Elaine-Krauss-TCG commented on front-end/src/app/transactions/transaction-group-d/transaction-group-d.component.ts
> +        'payee_last_name',
Good catch; it's been taken care of

2023-03-01 21:25 UTC, toddlees approved these changes

2023-03-02 16:18 UTC, mjtravers approved these changes

2023-03-02 16:18 UTC, merged