Feature/453,947 Add REFUND_TO_OTHER_POLITICAL_COMMITTEE transaction
fecgov/fecfile-web-app pull request #980
Opened 2023-04-12 21:04 UTC by mjtravers

#453 
#947

2023-04-17 14:26 UTC, Elaine-Krauss-TCG approved these changes

2023-04-18 13:23 UTC, toddlees approved these changes
Here's a suggested edit.  I think it's a little more self documenting: https://github.com/fecgov/fecfile-web-app/pull/985

I won't be offended if you disagree

2023-04-19 14:55 UTC, dheitzer approved these changes

2023-04-19 14:55 UTC, dheitzer approved these changes

2023-04-19 17:24 UTC, toddlees requested changes

2023-04-19 17:24 UTC, toddlees commented on front-end/src/app/shared/components/inputs/election-input/election-input.component.ts
> +    this.form.get('electionType')?.valueChanges.subscribe(() => {
these will leave hanging subscriptions without ```takeUntil(this.$destroy)```

2023-04-19 20:16 UTC, mjtravers commented on front-end/src/app/shared/components/inputs/election-input/election-input.component.ts
> +    this.form.get('electionType')?.valueChanges.subscribe(() => {
onDelete with destroy$ added

2023-04-19 20:28 UTC, toddlees approved these changes

2023-04-20 22:00 UTC, merged